CREATE SCHEMA IF NOT EXISTS `halmang` DEFAULT CHARACTER SET utf8mb4;

GRANT ALL ON *.* TO 'root'@'localhost' IDENTIFIED BY 'root' WITH GRANT OPTION;
GRANT ALL ON halmang.* TO 'root'@'localhost';
FLUSH PRIVILEGES;
